name: Linting

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang-format-15 \
            clang-tidy-15 \
            cppcheck \
            cmake \
            ninja-build \
            gcc-12 \
            g++-12

      - name: Check code formatting
        run: |
          find src tests -name "*.cpp" -o -name "*.hpp" -o -name "*.h" | \
          xargs clang-format-15 --dry-run --Werror

      - name: Configure for static analysis
        run: |
          export CC=gcc-12
          export CXX=g++-12
          cmake -B build \
            -DCMAKE_BUILD_TYPE=Debug \
            -DCMAKE_CXX_STANDARD=20 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -G Ninja

      - name: Run clang-tidy
        run: |
          find src -name "*.cpp" | head -10 | xargs clang-tidy-15 -p build || true

      - name: Run cppcheck
        run: |
          cppcheck --enable=all --std=c++20 --suppress=missingIncludeSystem \
            --suppress=unusedFunction --error-exitcode=1 src/ || true